apiVersion: v1
kind: Secret
metadata:
  name: {{ template "activemq-artemis.fullname" . }}
  labels:
    app: {{ template "activemq-artemis.fullname" . }}
    chart:  {{ template "activemq-artemis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.artemisUser }}
  artemis-user:  {{ .Values.artemisUser | b64enc | quote -}}
  {{ else }}
  artemis-user: {{ randAlphaNum 10 | b64enc | quote -}}
  {{- end -}}
  {{ if .Values.artemisPassword }}
  artemis-password:  {{ .Values.artemisPassword | b64enc | quote -}}
  {{ else }}
  artemis-password: {{ randAlphaNum 10 | b64enc | quote -}}
  {{ end }}
