apiVersion: v1
kind: Service
metadata:
  name: {{ template "activemq-artemis.fullname" . }}
  labels:
    app: {{ template "activemq-artemis.name" . }}
    chart: {{ template "activemq-artemis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: stomp
    port: 61613
    targetPort: 61613
    protocol: TCP
  selector:
    app: {{ template "activemq-artemis.name" . }}
    release: {{ .Release.Name }}
